name: TheOnly-Donations
version: 3.0.1
api-version: 1.13
author: aglerr
main: me.aglerr.donations.DonationPlugin
softdepend: [SkinsRestorer, PlaceholderAPI]

commands:
  donations:
    aliases: [donation]