
options:
  useUUID: true

# If head messages is disabled, we will use a message without the
# head skin instead, and head messages message line are limit to only 8
donationsMessage:
  messageWithAvatar:
    enabled: true
    messages:
      header: " "
      line1: " &6» &l{player} &ejust donated!"
      line2: " &6» Store: &7store.example.com"
      line3: ""
      line4: " &6&lMONTHLY GOAL &7(${goal_current_donation}/${goal_donation_goal})"
      line5: " {goal_progress_bar} &7{goal_percentage}%"
      line6: ""
      line7: " &6Product: {product_displayname} &7(${product_price})"
      line8: " &7(( Help us keep the server alive! ))"
      footer: " "
  messageWithoutAvatar:
    messages:
      - ""
      - " &6» &l{player} &7just donated!"
      - " &6» Store: &7store.example.com"
      - ""
      - " &6&lMONTHLY GOAL &7(${goal_current_donation}/${goal_donation_goal})"
      - " {goal_progress_bar} &7{goal_percentage}%"
      - ""
      - " &6Product: {product_displayname} &7(${product_price})"
      - ""
      - " &7(( Help us keep the server alive! ))"


# A list of all events that are will be played
# when donation happen.
events:
  effect:
    enabled: true
    effects:
      - "SPEED;3;30"
      - "JUMP;5;30"
      - "FAST_DIGGING;3;30"
      - "NIGHT_VISION;3;30"
  sound:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  titleBar:
    enabled: true
    title: "&e&l{player} just donated!"
    subTitle: "&fEveryone will receive special effects!"
    fadeIn: 20
    stay: 60
    fadeOut: 20
  command:
    enabled: true
    commands:
      - "broadcast &aThanks {player} for the donation, everyone will receive a key!"
      - "crazycrates giveall virtual vote 5"

donationGoal:
  enabled: true
  donationGoal: 500
  progressBar:
    barLength: 15
    symbol: '█'
    completedColor: GREEN
    notCompletedColor: RED
  commandsOnReach:
    - "broadcast &aWe have reached the donation goal!"
